# vi: set ft=ruby :

SERVER_NAME = "hello_server"

Vagrant.configure(2) do |config|

  config.vm.box = "ubuntu/trusty64"

  config.vm.define SERVER_NAME

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "1024"
  end

  config.vm.synced_folder "..", "/home/vagrant/hello"
  config.vm.network "forwarded_port", guest: 80, host: 8080

  config.vm.provision "ansible" do |ansible|
    ansible.verbose = "v"
    ansible.groups = {
      "webserverhosts" => [SERVER_NAME],
      "mysqlhosts" => [SERVER_NAME],
      "cacheserverhosts" => [SERVER_NAME]
    }

    ansible.limit = "all"
    ansible.playbook = "../ansible/playbook.yml"
  end

end
